//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.34014
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace RegiRide.Resources {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "4.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    public class AppResources {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal AppResources() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("RegiRide.Resources.AppResources", typeof(AppResources).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to city?.
        /// </summary>
        public static string AddressCity {
            get {
                return ResourceManager.GetString("AddressCity", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Addresses.
        /// </summary>
        public static string AddressListPageTitle {
            get {
                return ResourceManager.GetString("AddressListPageTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to name?.
        /// </summary>
        public static string AddressName {
            get {
                return ResourceManager.GetString("AddressName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Address.
        /// </summary>
        public static string AddressPageTitle {
            get {
                return ResourceManager.GetString("AddressPageTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to postal code?.
        /// </summary>
        public static string AddressPostalCode {
            get {
                return ResourceManager.GetString("AddressPostalCode", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to street and number?.
        /// </summary>
        public static string AddressStreet {
            get {
                return ResourceManager.GetString("AddressStreet", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to All the rides have been deleted..
        /// </summary>
        public static string AllRidesAreDeleted {
            get {
                return ResourceManager.GetString("AllRidesAreDeleted", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to RegiRide.
        /// </summary>
        public static string ApplicationTitle {
            get {
                return ResourceManager.GetString("ApplicationTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Are you sure, this will remove all registered rides?.
        /// </summary>
        public static string AreYouSureRemoveRides {
            get {
                return ResourceManager.GetString("AreYouSureRemoveRides", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The address could not be deleted, it is used by a registrated ride..
        /// </summary>
        public static string CannotDeleteAddressBecauseInUse {
            get {
                return ResourceManager.GetString("CannotDeleteAddressBecauseInUse", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Could not delete.
        /// </summary>
        public static string CannotDeleteTitle {
            get {
                return ResourceManager.GetString("CannotDeleteTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Are you sure?.
        /// </summary>
        public static string ConfirmDelete {
            get {
                return ResourceManager.GetString("ConfirmDelete", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Confirm Delete.
        /// </summary>
        public static string ConfirmDeleteTitle {
            get {
                return ResourceManager.GetString("ConfirmDeleteTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Remove all registrations.
        /// </summary>
        public static string DeleteAllRides {
            get {
                return ResourceManager.GetString("DeleteAllRides", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Dropbox folder.
        /// </summary>
        public static string DropboxFolder {
            get {
                return ResourceManager.GetString("DropboxFolder", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Export.
        /// </summary>
        public static string DropBoxPageTitle {
            get {
                return ResourceManager.GetString("DropBoxPageTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Dropbox folder to use for exporting registered rides.
        /// </summary>
        public static string ExportDropboxFolder {
            get {
                return ResourceManager.GetString("ExportDropboxFolder", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to To be able to export your rides you need to give RegiRide access to your Dropbox. You have to perform this action only once..
        /// </summary>
        public static string ExportDropboxNotification {
            get {
                return ResourceManager.GetString("ExportDropboxNotification", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Date, From Relation, From Street, From Postal Code, From City, To Relation, To Street, To Postal Code, To City, Start Milage, End Milage, Type, Remark.
        /// </summary>
        public static string ExportHeader {
            get {
                return ResourceManager.GetString("ExportHeader", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Loading.....
        /// </summary>
        public static string Loading {
            get {
                return ResourceManager.GetString("Loading", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Cannot connect to the Dropbox website, check your network connection..
        /// </summary>
        public static string NoNetworkAvailable {
            get {
                return ResourceManager.GetString("NoNetworkAvailable", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Uit.
        /// </summary>
        public static string Off {
            get {
                return ResourceManager.GetString("Off", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Aan.
        /// </summary>
        public static string On {
            get {
                return ResourceManager.GetString("On", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to date?.
        /// </summary>
        public static string RideDetailDate {
            get {
                return ResourceManager.GetString("RideDetailDate", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to end address?.
        /// </summary>
        public static string RideDetailEndAddress {
            get {
                return ResourceManager.GetString("RideDetailEndAddress", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to end milage?.
        /// </summary>
        public static string RideDetailEndMilage {
            get {
                return ResourceManager.GetString("RideDetailEndMilage", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Business.
        /// </summary>
        public static string RideDetailOptionBusiness {
            get {
                return ResourceManager.GetString("RideDetailOptionBusiness", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Private.
        /// </summary>
        public static string RideDetailOptionPrivate {
            get {
                return ResourceManager.GetString("RideDetailOptionPrivate", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Ride detail.
        /// </summary>
        public static string RideDetailPageTitle {
            get {
                return ResourceManager.GetString("RideDetailPageTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to remark?.
        /// </summary>
        public static string RideDetailRemark {
            get {
                return ResourceManager.GetString("RideDetailRemark", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to start address?.
        /// </summary>
        public static string RideDetailStartAddress {
            get {
                return ResourceManager.GetString("RideDetailStartAddress", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to start milage?.
        /// </summary>
        public static string RideDetailStartMilage {
            get {
                return ResourceManager.GetString("RideDetailStartMilage", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to type?.
        /// </summary>
        public static string RideDetailType {
            get {
                return ResourceManager.GetString("RideDetailType", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Rides.
        /// </summary>
        public static string RideListPageTitle {
            get {
                return ResourceManager.GetString("RideListPageTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Business.
        /// </summary>
        public static string RideTypeBusiness {
            get {
                return ResourceManager.GetString("RideTypeBusiness", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Private.
        /// </summary>
        public static string RideTypePrivate {
            get {
                return ResourceManager.GetString("RideTypePrivate", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Settings.
        /// </summary>
        public static string SettingsPageTitle {
            get {
                return ResourceManager.GetString("SettingsPageTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to A start address and an end address are required..
        /// </summary>
        public static string StartAddressAndEndAddressAreRequired {
            get {
                return ResourceManager.GetString("StartAddressAndEndAddressAreRequired", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The registrated rides are successfully exported to your dropbox..
        /// </summary>
        public static string SuccessfullExportedRides {
            get {
                return ResourceManager.GetString("SuccessfullExportedRides", resourceCulture);
            }
        }
    }
}
